### ISSUE TITLE
Add ETW to stats page

### ISSUE THREAD

**Issue by kmoore134** [truepool/website#16]
Add an estimated time to win widget to the stats page.

**Comment by undsoft** [comment]
https://dev.truepool.io/swagger/
TODO: 
1. We are currently querying /stats, we should be querying /info. Remove old method, associated interface, add new method and interface for /info - see `pool.service.ts`.
2. Replace usages - see stats.store.ts.
3. Update stats page to show new interesting number. For example, block height can be replace with `minutes_to_win`.

**Comment by feydkin** [comment]
Feature is live.
