### ISSUE TITLE
Add a dark mode to the website.

### ISSUE THREAD

**Issue by technolibre-chia** [truepool/website#18]
One of the most significant quality of life features of Space Pool is dark mode. Many of us find the blinding white of most pages to be off-putting and could discourage new members.

**Comment by undsoft** [comment]
TODO: use https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme to adjust styles for article and article list pages.

**Comment by undsoft** [comment]
Some other things that I've noticed on dev server.
1. The blue stats bar draws a lot of attention, looks like notification. I'd prefer a shade of black.
2. On leaderboard, borders on pagination buttons are too bright in dark mode.
3. When setting name on light theme, it used to be that page background was dark with white rectangle in the middle. Now it's all white.

**Comment by feydkin** [comment]
The feature is live
