### ISSUE TITLE
Add a "luck" metric to the stats page

### ISSUE THREAD

**Issue by edgarsuit** [truepool/website#40]
Add a "luck" metric to the stats page that measure win rate vs. expected win rate, similar to what space pool has: https://pool.space/

**Comment by WinterSnowfall** [comment]
Ah, you did beat me to it :). Seconded, in any case.

**Comment by undsoft** [comment]
Can be closed? Do we still need https://github.com/truepool/website/issues/56 ?

**Comment by feydkin** [comment]
We still need #56 because it's for historical luck, where this PR was for current/live luck. This is closed now thank you.
