### ISSUE TITLE
Use proper units for storage metrics

### ISSUE THREAD

**Issue by undsoft** [truepool/website#52]
I believe middleware returns numbers in TiB, while we use TB.
Check if this is so and update where necessary.

**Comment by chiawawah** [comment]
API says "farm_estimated_size": 49976431870790
Leader board says 45.45TB should say 45.45 TiB or be converted differently..
49976431870790B = 49.9764319TB
Which is closer to actual farm size currently...
484 * 106 GB = 51.304 TB
